Fix paste helper. Paste helper returns a tuple of 1 element which causes it to fail
  File
  line 868, in do_pastebin
      paste_url, removal_url = self.paster.paste(s)
      ValueError: need more than 1 value to unpack